# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'd09' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for d09

  target 'd09Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'd09UITests' do
    inherit! :search_paths
    # Pods for testing
  end

  # d09 pod
  pod 'atoulous2018', :path => './atoulous2018/'

end
